# MultiLUT Insurgency Optimized v1.8 Complete-Maps
# Minimal first test: no CAS, Levels or Vibrance.
# Escolha o mapa/perfil em ACTIVE_LUT_PROFILE no inicio do arquivo FX.
effects = MultiLUT

toggleKey = F3
enableOnLaunch = True

reshadeTexturePath = /home/felipe/.config/vkBasalt/reshade-shaders/Textures
reshadeIncludePath = /home/felipe/.config/vkBasalt/reshade-shaders/Shaders

MultiLUT = /home/felipe/.config/vkBasalt/reshade-shaders/Shaders/MultiLUT_Insurgency_Optimized.fx
